docs(github-app): webhook correction
Update GitHub App documentation to reflect that a GitHub App already has a built-in webhook that does not require creating a new webhook using the _Webhook_ permission. Furthermore, to take advantage of that built-in webhook, events must be enabled on the App's _Permissions_ page.

Otherwise, if you wanted to use a separate webhook created by Jenkins using the credentials of the GitHub App, you would need to enable the _Admin_ permission, or else you would get the following error and no webhook:

```
Failed to add GitHub webhook for GitHubRepositoryName[host=github.example.com,username=test,repository=test]
java.lang.NullPointerException: There are no credentials with admin access to manage hooks on GitHubRepositoryName[host=github.example.com,username=test,repository=test]
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:231)
	at org.jenkinsci.plugins.github.webhook.WebhookManager$2.applyNullSafe(WebhookManager.java:179)
	at org.jenkinsci.plugins.github.webhook.WebhookManager$2.applyNullSafe(WebhookManager.java:175)
```